# Generated by Django 5.2 on 2025-07-03 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('actor', 'actor'), ('director', 'director')], max_length=30)),
            ],
            options={
                'db_table': 'cast_member',
            },
        ),
    ]
