# Generated by Django 5.2 on 2025-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_member_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='type',
            field=models.CharField(choices=[('ACTOR', 'ACTOR'), ('DIRECTOR', 'DIRECTOR')], max_length=30),
        ),
    ]
