# Generated by Django 5.2 on 2025-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='categories',
        ),
        migrations.AddField(
            model_name='genre',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='category_app.category'),
        ),
    ]
